#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jan 28, 2018 06:07:36 PM


import sys, os
sys.path.append("..")

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global ClassiferBox
    ClassiferBox = StringVar()
    global DatasetBox
    DatasetBox = StringVar()
    global ThresholdBox
    ThresholdBox = StringVar()
    global LaneDetection
    LaneDetection = BooleanVar(value=1)
    global ObjectDetection
    ObjectDetection = BooleanVar(value=1)
    global ObjectVisual
    ObjectVisual = BooleanVar(value=0)
    global LaneVisual
    LaneVisual = BooleanVar(value=0)
    global DiagnosticMode
    DiagnosticMode = BooleanVar(value=0)
    global FrameRateOutput
    FrameRateOutput = IntVar(value=0)
    global cpd53
    cpd53 = StringVar()
    global spinbox
    spinbox = StringVar()
    global MonitorIDBox
    MonitorIDBox = StringVar()
    global WindowHeightBox
    WindowHeightBox = StringVar()
    global WindowWidthBox
    WindowWidthBox = StringVar()
    global TopOffsetBox
    TopOffsetBox = StringVar()
    global LeftOffsetBox
    LeftOffsetBox = StringVar()
    global che38
    che38 = StringVar()
    global CommandLineOutput
    CommandLineOutput = StringVar()
    global WindowCheck
    WindowCheck = IntVar()



def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

