#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Feb 25, 2018 04:38:19 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def init(top, gui, *args, **kwargs):
    global w, Warning_Interface, root
    w = gui
    Warning_Interface = top
    root = top

def destroy_window():
    # Function which closes the window.
    global Warning_Interface
    Warning_Interface.destroy()
    Warning_Interface = None

if __name__ == '__main__':
    import WarningInterface
    WarningInterface.vp_start_warning_interface()
