#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""




#############################################################################
## vTcl Code to Load Stock Images


if {![info exist vTcl(sourcing)]} {
#############################################################################
## Procedure:  vTcl:rename

proc ::vTcl:rename {name} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.
    regsub -all "\\." $name "_" ret
    regsub -all "\\-" $ret "_" ret
    regsub -all " " $ret "_" ret
    regsub -all "/" $ret "__" ret
    regsub -all "::" $ret "__" ret

    return [string tolower $ret]
}

#############################################################################
## Procedure:  vTcl:image:create_new_image

proc ::vTcl:image:create_new_image {filename {description {no description}} {type {}} {data {}}} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.
    # Does the image already exist?
    if {[info exists ::vTcl(images,files)]} {
        if {[lsearch -exact $::vTcl(images,files) $filename] > -1} { return }
    }
    if {![info exists ::vTcl(sourcing)] && [string length $data] > 0} {
        set object [image create  [vTcl:image:get_creation_type $filename]  -data $data]
    } else {
        # Wait a minute... Does the file actually exist?
        if {! [file exists $filename] } {
            # Try current directory
            set script [file dirname [info script]]
            set filename [file join $script [file tail $filename] ]
        }

        if {![file exists $filename]} {
            set description "file not found!"
            ## will add 'broken image' again when img is fixed, for
            ## now create empty
            set object [image create photo -width 1 -height 1]
        } else {
            set object [image create  [vTcl:image:get_creation_type $filename]  -file $filename]
        }
    }

    set reference [vTcl:rename $filename]
    set ::vTcl(images,$reference,image)       $object
    set ::vTcl(images,$reference,description) $description
    set ::vTcl(images,$reference,type)        $type
    set ::vTcl(images,filename,$object)       $filename

    lappend ::vTcl(images,files) $filename
    lappend ::vTcl(images,$type) $object
    set ::vTcl(imagefile,$object) $filename   ;# Rozen
    # return image name in case caller might want it
    return $object
}

#############################################################################
## Procedure:  vTcl:image:get_image

proc ::vTcl:image:get_image {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    set reference [vTcl:rename $filename]

    # Let's do some checking first
    if {![info exists ::vTcl(images,$reference,image)]} {
        # Well, the path may be wrong; in that case check
        # only the filename instead, without the path.

        set imageTail [file tail $filename]

        foreach oneFile $::vTcl(images,files) {
            if {[file tail $oneFile] == $imageTail} {
                set reference [vTcl:rename $oneFile]
                break
            }
        }
    }
    # Rozen. There follows a hack in case one wants to rerun a tcl
    # file which contains a file name where an image is expected.
    if {![info exists ::vTcl(images,$reference,image)]} {
        set ::vTcl(images,$reference,image)  [vTcl:image:create_new_image $filename]
    }
    return $::vTcl(images,$reference,image)
}

#############################################################################
## Procedure:  vTcl:image:get_creation_type

proc ::vTcl:image:get_creation_type {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    switch [string tolower [file extension $filename]] {
        .ppm -
        .jpg -
        .bmp -
        .gif    {return photo}
        .xbm    {return bitmap}
        default {return photo}
    }
}

foreach img {


            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

}
#############################################################################
## vTcl Code to Load User Images

catch {package require Img}

foreach img {

        {{$[pwd]/27294604_2005939912779799_980895550_3n.png} {file not found!} user {}}

            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family David -size 24 -weight bold -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Calibri Light} -size 22 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.tLa63
    set site_3_0 $base.tLa73
    set site_4_0 $site_3_0.cpd75
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 436x489+606+201
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1916 1054
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "DeepEyeUI" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::style configure TLabelframe -foreground #000000
    ttk::style configure TLabelframe -font TkDefaultFont
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tLa63 \
        -text Dataset -relief flat -width 230 -height 165 
    vTcl:DefineAlias "$top.tLa63" "DatasetFrame" vTcl:WidgetProc "DeepEyeUI" 1
    set site_3_0 $top.tLa63
    ttk::combobox $site_3_0.tCo64 \
        -values {'Nas' 'Inception-Resnet' 'Resnet101'} \
        -textvariable ClassiferBox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo64" "ClassifierCode" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::combobox $site_3_0.tCo65 \
        -values {'Coco' 'Kitti' {}} -textvariable DatasetBox -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo65" "DatasetCode" vTcl:WidgetProc "DeepEyeUI" 1
    spinbox $site_3_0.spi66 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground black -from 0.0 -highlightbackground black \
        -highlightcolor black -increment 0.01 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ThresholdBox -to 1.0 -values '.85' 
    vTcl:DefineAlias "$site_3_0.spi66" "Threshold" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::label $site_3_0.tLa70 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Classifier 
    vTcl:DefineAlias "$site_3_0.tLa70" "TLabel4" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::label $site_3_0.tLa71 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Dataset 
    vTcl:DefineAlias "$site_3_0.tLa71" "TLabel5" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::label $site_3_0.tLa72 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Threshold 
    vTcl:DefineAlias "$site_3_0.tLa72" "TLabel6" vTcl:WidgetProc "DeepEyeUI" 1
    place $site_3_0.tCo64 \
        -in $site_3_0 -x 90 -y 40 -width 113 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo65 \
        -in $site_3_0 -x 90 -y 75 -width 113 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi66 \
        -in $site_3_0 -x 90 -y 113 -width 55 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa70 \
        -in $site_3_0 -x 24 -y 40 -width 61 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa71 \
        -in $site_3_0 -x 30 -y 76 -width 50 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa72 \
        -in $site_3_0 -x 18 -y 112 -width 57 -height 19 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tLa73 \
        -text Input/Output -width 390 -height 155 
    vTcl:DefineAlias "$top.tLa73" "InputOutputFrame" vTcl:WidgetProc "DeepEyeUI" 1
    set site_3_0 $top.tLa73
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $site_3_0.cpd75 \
        -borderwidth 2 -relief groove -width 185 -height 115 
    vTcl:DefineAlias "$site_3_0.cpd75" "MonitorSizeFrame" vTcl:WidgetProc "DeepEyeUI" 1
    set site_4_0 $site_3_0.cpd75
    checkbutton $site_4_0.cpd53 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} \
        -command WindowHeight.configure(state='disabled') \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text {Set Custom Window Size?} -variable cpd53 
    vTcl:DefineAlias "$site_4_0.cpd53" "CustomWindowCheck" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::label $site_4_0.cpd54 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text Height 
    vTcl:DefineAlias "$site_4_0.cpd54" "TLabel7" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::label $site_4_0.cpd55 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text Width 
    vTcl:DefineAlias "$site_4_0.cpd55" "TLabel8" vTcl:WidgetProc "DeepEyeUI" 1
    spinbox $site_4_0.cpd56 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledbackground {#f0f0f0f0f0f0} \
        -disabledforeground {#a3a3a3} -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable WindowHeight -to 5000.0 
    vTcl:DefineAlias "$site_4_0.cpd56" "WindowHeight" vTcl:WidgetProc "DeepEyeUI" 1
    spinbox $site_4_0.cpd57 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable WindowWidth -to 5000.0 
    vTcl:DefineAlias "$site_4_0.cpd57" "WindowWidth" vTcl:WidgetProc "DeepEyeUI" 1
    place $site_4_0.cpd53 \
        -in $site_4_0 -x 0 -y 0 -width 181 -height 45 -anchor nw \
        -bordermode inside 
    place $site_4_0.cpd54 \
        -in $site_4_0 -x 10 -y 40 -width 43 -height 19 -anchor nw \
        -bordermode inside 
    place $site_4_0.cpd55 \
        -in $site_4_0 -x 16 -y 72 -width 43 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_4_0.cpd56 \
        -in $site_4_0 -x 69 -y 43 -width 95 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.cpd57 \
        -in $site_4_0 -x 69 -y 72 -width 95 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::label $site_3_0.cpd76 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Monitor ID} 
    vTcl:DefineAlias "$site_3_0.cpd76" "TLabel9" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::combobox $site_3_0.cpd77 \
        -textvariable MonitorIDBox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.cpd77" "MonitorId" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::label $site_3_0.tLa78 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Top Offest} 
    vTcl:DefineAlias "$site_3_0.tLa78" "TLabel1" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::label $site_3_0.tLa79 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Left Offset} 
    vTcl:DefineAlias "$site_3_0.tLa79" "TLabel2" vTcl:WidgetProc "DeepEyeUI" 1
    spinbox $site_3_0.spi80 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground black -from 0.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable TopOffset -to 5000.0 -values '0' 
    vTcl:DefineAlias "$site_3_0.spi80" "TopOffset" vTcl:WidgetProc "DeepEyeUI" 1
    spinbox $site_3_0.spi81 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground black -from 0.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable LeftOffset -to 5000.0 -values '0' 
    vTcl:DefineAlias "$site_3_0.spi81" "LeftOffset" vTcl:WidgetProc "DeepEyeUI" 1
    place $site_3_0.cpd75 \
        -in $site_3_0 -x 180 -y 26 -width 185 -relwidth 0 -height 115 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.cpd76 \
        -in $site_3_0 -x 16 -y 40 -width 61 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.cpd77 \
        -in $site_3_0 -x 90 -y 40 -width 63 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa78 \
        -in $site_3_0 -x 17 -y 72 -width 63 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa79 \
        -in $site_3_0 -x 19 -y 105 -width 59 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi80 \
        -in $site_3_0 -x 90 -y 70 -width 65 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi81 \
        -in $site_3_0 -x 89 -y 107 -width 65 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.cpd83 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#ec0006} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Exit 
    vTcl:DefineAlias "$top.cpd83" "ExitButton" vTcl:WidgetProc "DeepEyeUI" 1
    button $top.cpd84 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#33cf1d} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Run 
    vTcl:DefineAlias "$top.cpd84" "RunButton" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::label $top.tLa90 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text Tlabel \
        -image [vTcl:image:get_image [file join C:/ page 27294604_2005939912779799_980895550_3n.png]] 
    vTcl:DefineAlias "$top.tLa90" "EyeBall" vTcl:WidgetProc "DeepEyeUI" 1
    ttk::label $top.tLa91 \
        -background {#d9d9d9} -foreground {#000000} \
        -font $::vTcl(fonts,vTcl:font10,object) -relief flat -text DeepEye 
    vTcl:DefineAlias "$top.tLa91" "Title" vTcl:WidgetProc "DeepEyeUI" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa63 \
        -in $top -x 20 -y 300 -width 230 -relwidth 0 -height 165 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa73 \
        -in $top -x 20 -y 130 -width 390 -relwidth 0 -height 155 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd83 \
        -in $top -x 280 -y 400 -width 117 -relwidth 0 -height 54 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd84 \
        -in $top -x 280 -y 320 -width 117 -relwidth 0 -height 54 -relheight 0 \
        -anchor nw -bordermode inside 
    place $top.tLa90 \
        -in $top -x 11 -y 10 -width 106 -relwidth 0 -height 99 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa91 \
        -in $top -x 140 -y 20 -width 496 -relwidth 0 -height 99 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

